INSERT INTO PRODUCT VALUES(DEFAULT, 'bacon', 3.99, '8 pieces of bacon', FALSE);
INSERT INTO PRODUCT VALUES(DEFAULT, 'OrangeJuice', 2.99, '1 gallon', FALSE);
INSERT INTO PRODUCT VALUES(DEFAULT, 'HashBrowns', 1.99, '1 pund of taters', FALSE);
INSERT INTO PRODUCT VALUES(DEFAULT, 'Table', 29.99, '6 X 3 ft sturdy wood table', FALSE);
INSERT INTO PRODUCT VALUES(DEFAULT, 'Chair', 12.99, 'one chair', FALSE);
INSERT INTO PRODUCT VALUES(DEFAULT, 'Plate', 5.99, 'a set of 4', FALSE);

--DELETE FROM PRODUCT;